(defparameter *matrix* (make-array '(2 2) :initial-contents '((2 5) (1 3))))
(defparameter *vector* (vector 1 2))

(defun matrix-transpose (input)
  (let* ((m (array-dimension input 0))
         (n (array-dimension input 1))
         (output (make-array (list n m) :initial-element nil)))
    (dotimes (i n)
      (dotimes (j m)
        (setf (aref output i j)
              (aref input j i))))
    output))

(defparameter *m-t* (matrix-transpose *matrix*))

(defun matrix-multiplication (matrix vector)
  (let ((m-t (matrix-transpose matrix))
        (m (array-dimension matrix 0))
        (n (array-dimension matrix 1))
        (output (make-array (array-total-size vector) :initial-element 0)))
    (dotimes (i m)
      (dotimes (j n)
        (setf (aref output i)
              (+ (* (aref vector j) (aref m-t j i))
                 (aref output i)))))
    output))
(matrix-multiplication *matrix* *vector*)

(defun vector-multiplication (vector scalar)
  (let ((output (make-array (array-total-size vector) :initial-element 0)))
    (dotimes (i (array-total-size vector))
      (setf (aref output i)
            (* scalar (aref vector i))))
    output))
(vector-multiplication *vector* 2)

